"""update models

Revision ID: 205a71686b1c
Revises: 1056ab87e782
Create Date: 2024-10-30 23:47:56.500190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205a71686b1c'
down_revision: Union[str, None] = '1056ab87e782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_detection_run_image', 'face_detection_runs', ['image_id'], unique=False)
    with op.batch_alter_table('images') as batch_op:
        batch_op.drop_constraint('fk_images_last_detection_run_id', type_='foreignkey')
        batch_op.drop_column('last_detection_run_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images') as batch_op:
        batch_op.add_column(sa.Column('last_detection_run_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_images_last_detection_run_id', 'face_detection_runs', ['last_detection_run_id'], ['id'])
    op.drop_index('idx_detection_run_image', table_name='face_detection_runs')
    # ### end Alembic commands ###
